# config/database.yml

default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/test.sqlite3

production:
  primary: &primary_production
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    url: <%= ENV['DATABASE_URL'] %>

  cache:
    <<: *primary_production
    database: sakabakensaku_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: sakabakensaku_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: sakabakensaku_production_cable
    migrations_paths: db/cable_migrate