# config/database.yml

default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/test.sqlite3

# --- 重要: 本番環境 (Render) の設定 ---
production:
  # ここで adapter を postgresql に上書きするのが必須です
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: sakabakensaku_production
  username: sakabakensaku
  password: <%= ENV['SAKABAKENSAKU_DATABASE_PASSWORD'] %>
  # Renderでは以下の環境変数が自動で設定されるため、これを読み込ませます
  url: <%= ENV['DATABASE_URL'] %>